- name: Expense project setup
  hosts: all
  become: yes
  tasks:
    - name: disabling mysql default version
      ansible.builtin.shell: dnf module disable mysql -y
    - name: Enable NodeJS 18 version
      ansible.builtin.shell: dnf module enable nodejs:18 -y
    - name: Install node js
      ansible.builtin.dnf:
        name: nodeJS
        state: present
    - name: Copy backend service file
      ansible.builtin.copy:
        src: backend.service
        dest: /etc/systemd/system/backend.service
    - name: Add application user
      ansible.builtin.user:
        name: expense
    - name: delete old app directory
      ansible.builtin.file:
        path: /app
        state: absent
    - name: create app directory
      ansible.builtin.file:
        path: /app
        state: directory
    - name: down load and extract app content
      ansible.builtin.unarchive:
        src: https://expense-artifacts.s3.amazonaws.com/backend.zip
        dest: /app
        remote_src: yes
    - name: down load nodejs dependencies
      ansible.builtin.shell: npm install
      args:
        chdir: /app
    - name: Install mysql client
      ansible.builtin.dnf:
        name: mysql
        state: present
    - name: Load the schema
      ansible.builtin.shell: mysql -h mysql-dev.gdevops.online -uroot -p{{MYSQL_ROOT_PASSWORD}} < /app/schema/backend.sql
    - name: start backend service
      ansible.builtin.systemd:
        name: backend
        state: restarted
        enabled: yes
        daemon-reload: yes












