- name: Install Nginx
  ansible.builtin.dnf:
    name: nginx
    state: present

- name: Copying reverse proxy nginx
  ansible.builtin.template:
    src: expense.conf
    dest: /etc/nginx/default.d/expense.conf

- name: Import common role app pre-requisites
  ansible.builtin.import_role:
    name: common
    tasks_from: app-prereq
  vars:
    app_dir: /user/share/nginx/html
    component: frontend

- name: start Nginx
  ansible.builtin.systemd:
    name: nginx
    state: restarted
    enabled: yes

- name: Import elk role file beat
  ansible.builtin.import_role:
    name: elk
    tasks_from: filebeat


- name: Import prometheus node exported
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node-exporter



