- name: copy prometheus configuration file
  ansible.builtin.template:
    src: prometheus.yml
    dest: /opt/prometheus/prometheus.yml

- name: Copy Alerts rules
  ansible.builtin.template:
    src: alerts-rules.yml
    dest: /opt/prometheus/alerts-rules.yml

- name: Restart prometheus
  ansible.builtin.systemd:
    name: prometheus
    state: restarted
    enabled: yes

